#!/usr/bin/env node
"use strict";

/*
 * Build the storm-independent Census population surface used by the browser.
 *
 * This intentionally calls the authoritative implementation in
 * outage_location_model.js.  Keeping preprocessing and runtime allocation in
 * one implementation prevents a silent Python/JavaScript math divergence.
 * The output is the unsmoothed population mass on the fixed HRRR grid;
 * scenario-selected smoothing is still performed and reported by the model.
 *
 * Usage:
 *   python 11_fetch_census_population.py
 *   node 11_build_census_population_grid.js
 */
const fs = require("node:fs");
const path = require("node:path");

const model = require("./outage_location_model.js");

const ROOT = __dirname;
const DATA = path.join(ROOT, "data");
const blocks = JSON.parse(fs.readFileSync(path.join(DATA, "connecticut_census_blocks.json"), "utf8"));
const boundary = JSON.parse(fs.readFileSync(path.join(DATA, "connecticut_land_boundary.json"), "utf8"));

// The timeline asset is browser JavaScript rather than JSON.  Supplying the
// expected global lets Node load its grid definition without parsing source.
global.window = globalThis;
require("./data/connecticut_storm_timelines.js");
const weatherGrid = globalThis.CONNECTICUT_STORM_TIMELINES.grid;
const latitudes = weatherGrid.lats;
const longitudes = weatherGrid.lons;
const mask = model.buildConnecticutMask(boundary, latitudes, longitudes);
const populationPersons = model.rasterizePopulationPersons(blocks, latitudes, longitudes, mask);
const flatPopulation = populationPersons.flat();
const totalPopulation = flatPopulation.reduce((sum, value) => sum + value, 0);
const expectedPopulation = blocks.reduce((sum, block) => sum + block.pop, 0);

if (Math.abs(totalPopulation - expectedPopulation) > 1e-6) {
  throw new Error(
    `Bilinear allocation failed population conservation: ${totalPopulation} vs ${expectedPopulation}`,
  );
}

const output = {
  schema: "connecticut_census_block_population_grid_v1",
  schemaVersion: 1,
  source: {
    dataset: "2020 Census P.L. 94-171 Redistricting Data",
    geography: "Census block",
    coordinateRepresentation: "Census-provided internal point",
    boundaryMask: "data/connecticut_land_boundary.json",
    allocation: "bilinear to four surrounding valid HRRR nodes with boundary renormalization",
    blockCount: blocks.length,
    populatedBlockCount: blocks.filter((block) => block.pop > 0).length,
    zeroPopulationBlockCount: blocks.filter((block) => block.pop === 0).length,
    totalPopulationPersons: expectedPopulation,
  },
  grid: {
    latitudes,
    longitudes,
    rows: latitudes.length,
    columns: longitudes.length,
    storage: "row-major flat array; index = row * columns + column",
  },
  connecticutMask: mask.flat().map((inside) => inside ? 1 : 0),
  populationPersons: flatPopulation,
};

const json = `${JSON.stringify(output, null, 2)}\n`;
const javascript = [
  "// Unsmoothed 2020 Census-block population bilinearly allocated to the HRRR grid.",
  "// Generated by 11_build_census_population_grid.js; population is in persons.",
  `window.CONNECTICUT_CENSUS_POPULATION_GRID = ${JSON.stringify(output)};`,
  "",
].join("\n");

fs.writeFileSync(path.join(DATA, "connecticut_census_population_grid.json"), json);
fs.writeFileSync(path.join(DATA, "connecticut_census_population_grid.js"), javascript);
console.log(
  `Wrote ${output.grid.rows}x${output.grid.columns} population grid from `
  + `${output.source.blockCount.toLocaleString()} blocks; total ${totalPopulation.toFixed(6)} persons.`,
);
