# -*- coding: utf-8 -*-
"""Wind_Rain_Visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBcp6KOJojJqtwCIx-1AIlEkS0-sdb0v

# Video  Transformers: HRRR Wind & Rain Data Visualization
---------------

This is a script to show you how to:
1) Download real-world hourly historic weather data
2) Make a GIF
3) Displays the GIF
"""

!pip uninstall -y herbie
!pip install herbie-data
from herbie import Herbie
!pip install cartopy

import os
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import imageio
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from herbie import Herbie
from datetime import datetime, timedelta
from matplotlib.colors import LinearSegmentedColormap
from google.colab import drive
import gc
import shutil

"""## Dependencies"""

import importlib.metadata as m

pkgs = [
    "numpy",
    "xarray",
    "cfgrib",
    "eccodes",
    "matplotlib",
    "cartopy",
    "herbie-data",
    "imageio",
]

for pkg in pkgs:
    try:
        print(f"{pkg}: {m.version(pkg)}")
    except:
        print(f"{pkg}: NOT INSTALLED")

"""# Grab a Year of Data
Save the grib files (compressed data format for images, popular with certain scientific datasets) and create a folder of images. Then - make a GIF!
"""

import os, gc, shutil, psutil
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import imageio.v2 as imageio
from datetime import datetime, timedelta
from herbie import Herbie

# --- SETTINGS ---
os.environ["ECCODES_DEFINITION_PATH"] = "/usr/local/share/eccodes/definitions"
os.environ["ECCODES_SAMPLES_PATH"] = "/usr/local/share/eccodes/samples"

base_dir = "/content/drive/MyDrive/OPIM5516/M_T/M_T_Wind_Dorian_Test"
img_dir = os.path.join(base_dir, "img_data")
grib_dir = os.path.join(base_dir, "grib_data")
video_dir = os.path.join(base_dir, "monthly_gifs")

os.makedirs(img_dir, exist_ok=True)
os.makedirs(grib_dir, exist_ok=True)
os.makedirs(video_dir, exist_ok=True)

# CHANGE THE DISPLAY DATE RANGE HERE
start_date = datetime(2019, 9, 1, 0)
end_date = datetime(2019, 9, 7, 23)

# Southeast / Florida region
lon_min, lon_max = -90, -70
lat_min, lat_max = 24, 38

# Downsample factor
# Larger number = faster but blurrier
skip = 4

img_files = []
t_step = start_date

while t_step <= end_date:
    timestamp_str = f"{t_step:%Y%m%d_%H}"
    png_path = os.path.join(img_dir, f"wind_{timestamp_str}.png")
    grib_path = os.path.join(grib_dir, f"wind_{timestamp_str}.grib2")

    print(f"Processing {timestamp_str}...")

    try:
        # HRRR surface data for this hour
        H = Herbie(
            t_step,
            model="hrrr",
            product="sfc",
            fxx=0,
            priority="aws",
            verbose=False
        )

        # Download 10-meter U and V wind components
        wind_file = H.download(":(?:U|V)GRD:10 m above ground")

        if not os.path.exists(grib_path):
            shutil.copy(wind_file, grib_path)

        # Open the wind data
        with xr.open_dataset(
            wind_file,
            engine="cfgrib",
            backend_kwargs={
                "filter_by_keys": {
                    "typeOfLevel": "heightAboveGround",
                    "level": 10
                }
            }
        ) as ds:

            u10 = ds["u10"]
            v10 = ds["v10"]

            # Calculate total wind speed
            wind_speed_ms = np.sqrt(u10**2 + v10**2)
            wind_speed_mph = wind_speed_ms * 2.23694

            # Convert longitude from 0–360 to -180–180
            lon = (((ds.longitude + 180) % 360) - 180).compute()
            lat = ds.latitude.compute()

            # Find grid cells inside our region
            region_mask = (
                (lon >= lon_min) & (lon <= lon_max) &
                (lat >= lat_min) & (lat <= lat_max)
            )

            # Convert the mask into row/column positions
            yy, xx = np.where(region_mask.values)

            if len(yy) == 0 or len(xx) == 0:
                raise ValueError("No HRRR grid points found inside the selected map region.")

            # Get the rectangular box around the region
            y0, y1 = yy.min(), yy.max() + 1
            x0, x1 = xx.min(), xx.max() + 1

            # Crop and downsample the wind + coordinates
            wind_region = wind_speed_mph.isel(
                y=slice(y0, y1, skip),
                x=slice(x0, x1, skip)
            ).compute()

            lon_region = lon.isel(
                y=slice(y0, y1, skip),
                x=slice(x0, x1, skip)
            ).values

            lat_region = lat.isel(
                y=slice(y0, y1, skip),
                x=slice(x0, x1, skip)
            ).values

            wind_values = wind_region.values

        # --- MAKE MAP ---
        fig = plt.figure(figsize=(9, 7))
        ax = plt.axes(projection=ccrs.PlateCarree())

        ax.set_extent([lon_min, lon_max, lat_min, lat_max], crs=ccrs.PlateCarree())

        ax.add_feature(cfeature.STATES.with_scale("50m"), linewidth=0.5)
        ax.add_feature(cfeature.COASTLINE.with_scale("50m"))
        ax.add_feature(cfeature.BORDERS.with_scale("50m"))

        mesh = ax.pcolormesh(
            lon_region,
            lat_region,
            wind_values,
            transform=ccrs.PlateCarree(),
            cmap="viridis",
            vmin=0,
            vmax=80,
            shading="auto"
        )

        cbar = plt.colorbar(mesh, ax=ax, shrink=0.75)
        cbar.set_label("10m Wind Speed (mph)")

        plt.title(f"HRRR 10m Wind Speed | {t_step:%Y-%m-%d %H}Z")

        plt.savefig(png_path, bbox_inches="tight", dpi=120)
        plt.close("all")

        img_files.append(png_path)
        print(f"✅ Saved image: {png_path}")

        del wind_speed_ms, wind_speed_mph, wind_region, wind_values, lon_region, lat_region
        gc.collect()

    except Exception as e:
        print(f"⚠️ Failed {timestamp_str}: {e}")
        plt.close("all")

    t_step += timedelta(hours=1)

# --- BUILD TEST GIF ---
if img_files:
    gif_path = os.path.join(video_dir, "wind_animation_dorian_test.gif")
    print("Creating test GIF...")

    with imageio.get_writer(gif_path, mode="I", duration=300, loop=0) as writer:
        for file in sorted(img_files):
            writer.append_data(imageio.imread(file))

    print(f"✅ Saved GIF: {gif_path}")
else:
    print("No images were created, so no GIF was made.")

print("Done.")
print(f"Current Memory: {psutil.virtual_memory().used / 1e9:.2f} GB")

import os, gc, shutil, psutil
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import imageio.v2 as imageio
from datetime import datetime, timedelta
from herbie import Herbie

# --- SETTINGS ---
os.environ["ECCODES_DEFINITION_PATH"] = "/usr/local/share/eccodes/definitions"
os.environ["ECCODES_SAMPLES_PATH"] = "/usr/local/share/eccodes/samples"

base_dir = "/content/drive/MyDrive/OPIM5516/M_T/M_T_Rain_Dorian_Test"
img_dir = os.path.join(base_dir, "img_data")
grib_dir = os.path.join(base_dir, "grib_data")
video_dir = os.path.join(base_dir, "monthly_gifs")

os.makedirs(img_dir, exist_ok=True)
os.makedirs(grib_dir, exist_ok=True)
os.makedirs(video_dir, exist_ok=True)

# Match this to the wind cell.
# This is still the short test window.
start_date = datetime(2019, 9, 1, 0)
end_date = datetime(2019, 9, 7, 23)

# Southeast / Florida region
lon_min, lon_max = -90, -70
lat_min, lat_max = 24, 38

# Downsample factor
skip = 4

img_files = []
t_step = start_date

while t_step <= end_date:
    timestamp_str = f"{t_step:%Y%m%d_%H}"
    png_path = os.path.join(img_dir, f"rain_{timestamp_str}.png")
    grib_path = os.path.join(grib_dir, f"rain_{timestamp_str}.grib2")

    print(f"Processing rain for {timestamp_str}...")

    try:
        # For hourly rainfall ending at t_step, use the previous model run with fxx=1
        run_time = t_step - timedelta(hours=1)

        H = Herbie(
            run_time,
            model="hrrr",
            product="sfc",
            fxx=1,
            priority="aws",
            verbose=False
        )

        # Download hourly accumulated precipitation
        rain_file = H.download("APCP:surface")

        if not os.path.exists(grib_path):
            shutil.copy(rain_file, grib_path)

        with xr.open_dataset(
            rain_file,
            engine="cfgrib",
            backend_kwargs={
                "filter_by_keys": {
                    "typeOfLevel": "surface"
                }
            }
        ) as ds:

            # Usually the precipitation variable is named "tp"
            # but this makes it robust in case cfgrib names it differently.
            possible_names = ["tp", "apcp", "unknown"]

            rain_var_name = None
            for name in possible_names:
                if name in ds.data_vars:
                    rain_var_name = name
                    break

            if rain_var_name is None:
                rain_var_name = list(ds.data_vars)[0]

            rain_mm = ds[rain_var_name]

            # HRRR precipitation is usually in kg/m^2, which equals mm of water.
            # Convert mm to inches for easier interpretation.
            rain_inches = rain_mm / 25.4

            # Convert longitude from 0–360 to -180–180
            lon = (((ds.longitude + 180) % 360) - 180).compute()
            lat = ds.latitude.compute()

            region_mask = (
                (lon >= lon_min) & (lon <= lon_max) &
                (lat >= lat_min) & (lat <= lat_max)
            )

            yy, xx = np.where(region_mask.values)

            if len(yy) == 0 or len(xx) == 0:
                raise ValueError("No HRRR grid points found inside the selected map region.")

            y0, y1 = yy.min(), yy.max() + 1
            x0, x1 = xx.min(), xx.max() + 1

            rain_region = rain_inches.isel(
                y=slice(y0, y1, skip),
                x=slice(x0, x1, skip)
            ).compute()

            lon_region = lon.isel(
                y=slice(y0, y1, skip),
                x=slice(x0, x1, skip)
            ).values

            lat_region = lat.isel(
                y=slice(y0, y1, skip),
                x=slice(x0, x1, skip)
            ).values

            rain_values = rain_region.values

        # --- MAKE MAP ---
        fig = plt.figure(figsize=(9, 7))
        ax = plt.axes(projection=ccrs.PlateCarree())

        ax.set_extent([lon_min, lon_max, lat_min, lat_max], crs=ccrs.PlateCarree())

        ax.add_feature(cfeature.STATES.with_scale("50m"), linewidth=0.5)
        ax.add_feature(cfeature.COASTLINE.with_scale("50m"))
        ax.add_feature(cfeature.BORDERS.with_scale("50m"))

        mesh = ax.pcolormesh(
            lon_region,
            lat_region,
            rain_values,
            transform=ccrs.PlateCarree(),
            cmap="Blues",
            vmin=0,
            vmax=1.0,
            shading="auto"
        )

        cbar = plt.colorbar(mesh, ax=ax, shrink=0.75)
        cbar.set_label("1-hour Rainfall (inches)")

        plt.title(f"HRRR 1-hour Rainfall | Ending {t_step:%Y-%m-%d %H}Z")

        plt.savefig(png_path, bbox_inches="tight", dpi=120)
        plt.close("all")

        img_files.append(png_path)
        print(f"✅ Saved image: {png_path}")

        del rain_mm, rain_inches, rain_region, rain_values, lon_region, lat_region
        gc.collect()

    except Exception as e:
        print(f"⚠️ Failed rain {timestamp_str}: {e}")
        plt.close("all")

    t_step += timedelta(hours=1)

# --- BUILD RAIN GIF ---
if img_files:
    gif_path = os.path.join(video_dir, "rain_animation_dorian_test.gif")
    print("Creating rain GIF...")

    with imageio.get_writer(gif_path, mode="I", duration=300, loop=0) as writer:
        for file in sorted(img_files):
            writer.append_data(imageio.imread(file))

    print(f"✅ Saved rain GIF: {gif_path}")
else:
    print("No rain images were created, so no rain GIF was made.")

print("Done.")
print(f"Current Memory: {psutil.virtual_memory().used / 1e9:.2f} GB")

"""# Data Visualization"""

import os, glob, base64
from IPython.display import HTML, display

# --- FOLDERS WHERE YOUR GIFS ARE SAVED ---
wind_gif_dir = "/content/drive/MyDrive/OPIM5516/M_T/M_T_Wind_Dorian_Test/monthly_gifs"
rain_gif_dir = "/content/drive/MyDrive/OPIM5516/M_T/M_T_Rain_Dorian_Test/monthly_gifs"

# --- FIND THE MOST RECENT GIF IN EACH FOLDER ---
def latest_gif(folder):
    gifs = glob.glob(os.path.join(folder, "*.gif"))
    if not gifs:
        raise FileNotFoundError(f"No GIFs found in: {folder}")
    return max(gifs, key=os.path.getmtime)

wind_gif_path = latest_gif(wind_gif_dir)
rain_gif_path = latest_gif(rain_gif_dir)

print("Wind GIF:", wind_gif_path)
print("Rain GIF:", rain_gif_path)

# --- CONVERT GIFS SO COLAB CAN DISPLAY THEM CLEANLY ---
def gif_to_base64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

wind_b64 = gif_to_base64(wind_gif_path)
rain_b64 = gif_to_base64(rain_gif_path)

# --- DISPLAY SIDE BY SIDE ---
html = f"""
<h2>Hurricane Dorian Weather Overlays</h2>

<div style="display: flex; gap: 24px; align-items: flex-start;">

  <div style="width: 50%;">
    <h3>HRRR 10m Wind Speed</h3>
    <img src="data:image/gif;base64,{wind_b64}" style="width: 100%; border: 1px solid #ccc;">
    <p style="font-size: 12px;">{wind_gif_path}</p>
  </div>

  <div style="width: 50%;">
    <h3>HRRR 1-hour Rainfall</h3>
    <img src="data:image/gif;base64,{rain_b64}" style="width: 100%; border: 1px solid #ccc;">
    <p style="font-size: 12px;">{rain_gif_path}</p>
  </div>

</div>
"""

display(HTML(html))